package com.pahanaedu.billing.model;

/**
 * Represents a Cashier user in the billing system.
 * Responsible for managing billing and customer interactions.
 * Passwords should be securely hashed and managed in production.
 */
public class Cashier {

    private final int cashierId;  // id is immutable once set
    private String username;
    private String password; // store hashed password in real applications
    private String name;
    private String email;

    /**
     * Full constructor to initialize all fields.
     *
     * @param cashierId Unique cashier identifier
     * @param username cashier username/login
     * @param password cashier password (hashed in real use)
     * @param name cashier full name
     * @param email cashier email address
     */
    public Cashier(int cashierId, String username, String password, String name, String email) {
        this.cashierId = cashierId;
        this.username = username;
        this.password = password;
        this.name = name;
        this.email = email;
    }

    /**
     * Constructor without `cashierId` if IDs are generated by the database.
     */
    public Cashier(String username, String password, String name, String email) {
        this.cashierId = 0; // default or placeholder value
        this.username = username;
        this.password = password;
        this.name = name;
        this.email = email;
    }

    /**
     * Default constructor (frameworks or setters can set properties later).
     */
    public Cashier() {
        this.cashierId = 0;
    }

    // Getters
    public int getCashierId() {
        return cashierId;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    // Setters
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Sets the cashier password.
     * In real applications, hash the password before setting it.
     *
     * @param password new password or hashed password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    // Example business logic methods

    /**
     * Example method where cashier generates a bill.
     */
    public void generateBill() {
        System.out.println("Cashier is generating a bill...");
        // Connect with BillingService or DAO layer here
    }

    /**
     * Process customer payment interaction.
     */
    public void processPayment() {
        System.out.println("Cashier is processing payment...");
        // Payment processing logic or service calls
    }

    /**
     * View customer details as part of cashier duties.
     */
    public void viewCustomerDetails() {
        System.out.println("Cashier is viewing customer details...");
        // Connect with CustomerDAO or service to fetch data
    }

    @Override
    public String toString() {
        // Exclude password for security reasons
        return "Cashier{" +
                "cashierId=" + cashierId +
                ", username='" + username + '\'' +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}
